name: pythonworkshop_dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - pandas
  - biopython
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - nbconvert
  - nbformat
  - traitlets
  - ipykernel